# Generated by Django 3.2.5 on 2022-07-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KocwAllList',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(blank=True, max_length=100, null=True)),
                ('course_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=100, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('taxon', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('popular_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kocw_all_list',
                'managed': False,
            },
        ),
    ]
