# Generated by Django 4.0.5 on 2022-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KocwAllList',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(blank=True, max_length=100, null=True)),
                ('course_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=100, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('taxon', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('popular_score', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
