# Generated by Django 4.0.5 on 2022-07-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kocw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kocwalllist',
            options={'managed': False},
        ),
    ]
